# Workflow to build at each commit in master the application

name: CI build micro backup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build server
    - name: Build micro backup
      run: |
        echo Run build micro backup
        cd src/main
        export GOOS=linux
        export GOARCH=arm
        go build -o micro_backup main.go
        cd ../../
        mkdir artifacts
        echo Copy backup artifact in artifacts/
        mv src/main/micro_backup artifacts

    # Upload artifact
    - uses: actions/upload-artifact@v1
      with:
        name: Artifacts micro backup
        path: artifacts
